### ISSUE TITLE
Build and boot options

### ISSUE THREAD

**Issue by Zubnix** [strelec/dell-xps-15-kernel-config#1]
What are the build and/or boot options used in this config? ie if I'm using uefi+grub & genkernel, what genkernel build commands should I (not) use? Or is this config for a specific uefi only build(?)

**Comment by strelec** [comment]
Do not use genkernel, use gentoo-sources.

This config should work both as a classical image, or as UEFI image (that you put onto the EFI partition).

All parameters are already embeded in the config, see here: https://github.com/strelec/dell-xps-15-kernel-config/blob/master/Linux%204.16/.config#L549

If you have never configured your own kernel, take a day off, it will take some time.

**Comment by Zubnix** [comment]
I was having some trouble getting it to boot using genkernel because it kept complaining about not finding the root device uuid. I did indeed noticed all config parameters are build in (including the partition uuid, which I assume will not work for anybody aside you... ) I'll see if I can get it working using the classic approach with an adjusted partuuid.

As far as my 10+y experience in getting gentoo (kernels) to work on a laptop exactly as you want them, it will usually take a day regardless if you've done it before or not... :wink:
