### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by bpinto** [strelec/dell-xps-15-kernel-config#2]
Hi there, I was wondering if you are still having the issue you mention on your README:

> To make sound working, you have to suspend the device and wake it up again. Most probably a kernel bug.

I have the same laptop and my config is [here](https://github.com/bpinto/dotfiles/blob/master/gentoo/usr/src/linux/.config) and I haven't experienced this but my config is not as slim as yours.

I'm asking because I'm thinking about going through the exhaustive process of comparing my kernel config with yours and enabling anything that I might need and you do not have enabled.

**Comment by strelec** [comment]
Bruno, thanks for your input.

I think that there is no need to do the binary search on config to find the difference.

I am pretty sure that the reason for the sound bug is that I have chosen to compile-in the sound drivers (=Y), as opposed to as a module (=M).

**Comment by bpinto** [comment]
That makes sense, okay, thanks!
